services:
  paytrace-rabbitmq:
    image: dhi.io/rabbitmq:4.2
    hostname: paytrace-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro